all:

  host:
    protocol: http
    host: example.com
    port: 80

  app:
    welcome_title: "*This text can be configured via the general settings*"
    welcome_text: "*This text can be configured via the general settings*"
    current_history_length: 5
    max_foreground_group_download_size: 10
    max_file_upload_size: "100"

    sources:
      release: "https://github.com/coneda/kor/releases/tag/{{version}}"
      pre_release: "https://github.com/coneda/kor/commit/{{commit}}"
      default: "https://github.com/coneda/kor"

  maintainer:
    name: Example Organization
    mail: admin@example.com
    legal_text: Beispieltext
    about_text: Beispieltext

  auth:
    session_lifetime: 2:00:00
    publishment_lifetime: 14
    default_groups: []

  # google_analytics:
  #   id: "12345"

  # piwik:
  #   url: "https://analytics.example.com"
  #   id: "1"

  logging:
    file: log/kor.log
    # possible options: debug < info < warn < error < fatal < (all other entries)
    level: debug

  umask: 0002

  cache_dir: tmp/cache
  tmp_dir: tmp/kor
  custom_css_file: data/custom.css

  kind_settings:
    defaults:
      dating_label: Dating
      name_label: Name
      distinct_name_label: distinct Name

  limits:
    max_file_upload_size: 30
    max_download_group_size: 80

  search:
    entity_name: "Name / Titel / UUID"


production:
  mail:
    delivery_method: smtp
    smtp_settings:
      host: 127.0.0.1
      port: 25
      enable_starttls_auto: false
      # domain: localhost


test:
  auth:
    sources:
      remote_user:
        type: 'env'
        user: ['REMOTE_USER']
        mail: ['mail']
        full_name: ['full_name']
        splitter: '[,;]+'
        map_to: 'ldap'
      credentials_via_file:
        type: script
        script: spec/fixtures/auth_script.file
        map_to: ldap
      credentials_via_env:
        script: spec/fixtures/auth_script.direct
        map_to: ldap

  app:
    default_locale: en
    gallery:
      primary_relations: ['shows']
      secondary_relations: ['has been created by']

    welcome_title: "Welcome"
    welcome_text: "This is a testing installation"

    current_history_length: 5
    max_foreground_group_download_size: 10

  maintainer:
    name: Example Organization
    mail: admin@example.com

  mail:
    delivery_method: test
